---
# tasks file for ansible-role-R
- name: Gather OS specific variables
  include_vars: '{{ item }}'
  with_first_found:
  - '{{ ansible_distribution|lower }}-{{ ansible_distribution_version }}.yml'
  - '{{ ansible_distribution|lower }}-{{ ansible_distribution_major_version }}.yml'
  - '{{ ansible_distribution|lower }}.yml'
  - '{{ ansible_os_family|lower }}.yml'
  - '{{ ansible_os_family|lower }}-{{ansible_distribution_major_version}}.yml'

- include_tasks: configure_apt.yml
  when: ansible_pkg_mgr == 'apt'